// Multi-language translation dictionaries and dynamic currency system for CoinCIKOX

export type SupportedLang = 
  | "id" | "en" | "de" | "es" | "fr" | "it" | "pt" | "ru" | "zh" 
  | "ja" | "ko" | "ar" | "hi" | "tr" | "nl" | "pl" | "th" | "vi";

export type SupportedCurrency = 
  | "USD" | "IDR" | "EUR" | "GBP" | "JPY" | "AUD" | "CAD" | "CHF" | "CNY" | "HKD" 
  | "NZD" | "SGD" | "KRW" | "INR" | "BRL" | "RUB" | "ZAR" | "TRY" | "PLN" | "PHP" 
  | "THB" | "MYR" | "VND" | "SAR" | "AED" | "BTC" | "ETH";

export const SUPPORTED_LANGUAGES: Record<SupportedLang, { name: string; flag: string }> = {
  id: { name: "Bahasa Indonesia", flag: "🇮🇩" },
  en: { name: "English", flag: "🇺🇸" },
  de: { name: "Deutsch (German)", flag: "🇩🇪" },
  es: { name: "Español (Spanish)", flag: "🇪🇸" },
  fr: { name: "Français (French)", flag: "🇫🇷" },
  it: { name: "Italiano (Italian)", flag: "🇮🇹" },
  pt: { name: "Português (Portuguese)", flag: "🇵🇹" },
  ru: { name: "Русский (Russian)", flag: "🇷🇺" },
  zh: { name: "简体中文 (Chinese)", flag: "🇨🇳" },
  ja: { name: "日本語 (Japanese)", flag: "🇯🇵" },
  ko: { name: "한국어 (Korean)", flag: "🇰🇷" },
  ar: { name: "العربية (Arabic)", flag: "🇸🇦" },
  hi: { name: "हिन्दी (Hindi)", flag: "🇮🇳" },
  tr: { name: "Türkçe (Turkish)", flag: "🇹🇷" },
  nl: { name: "Nederlands (Dutch)", flag: "🇳🇱" },
  pl: { name: "Polski (Polish)", flag: "🇵🇱" },
  th: { name: "ไทย (Thai)", flag: "🇹🇭" },
  vi: { name: "Tiếng Việt (Vietnamese)", flag: "🇻🇳" },
};

export const SUPPORTED_CURRENCIES: Record<SupportedCurrency, { name: string; symbol: string }> = {
  USD: { name: "US Dollar", symbol: "$" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  EUR: { name: "Euro", symbol: "€" },
  GBP: { name: "Pound Sterling", symbol: "£" },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  AUD: { name: "Australian Dollar", symbol: "A$" },
  CAD: { name: "Canadian Dollar", symbol: "C$" },
  CHF: { name: "Swiss Franc", symbol: "CHF" },
  CNY: { name: "Chinese Yuan", symbol: "¥" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
  SGD: { name: "Singapore Dollar", symbol: "S$" },
  KRW: { name: "South Korean Won", symbol: "₩" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  ZAR: { name: "South African Rand", symbol: "R" },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  PLN: { name: "Polish Złoty", symbol: "zł" },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  THB: { name: "Thai Baht", symbol: "฿" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM" },
  VND: { name: "Vietnamese Đồng", symbol: "₫" },
  SAR: { name: "Saudi Riyal", symbol: "SR" },
  AED: { name: "UAE Dirham", symbol: "DH" },
  BTC: { name: "Bitcoin", symbol: "₿" },
  ETH: { name: "Ethereum", symbol: "Ξ" },
};

export const CURRENCY_SYMBOLS: Record<SupportedCurrency, string> = {
  USD: "$",
  IDR: "Rp",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "A$",
  CAD: "C$",
  CHF: "CHF",
  CNY: "¥",
  HKD: "HK$",
  NZD: "NZ$",
  SGD: "S$",
  KRW: "₩",
  INR: "₹",
  BRL: "R$",
  RUB: "₽",
  ZAR: "R",
  TRY: "₺",
  PLN: "zł",
  PHP: "₱",
  THB: "฿",
  MYR: "RM",
  VND: "₫",
  SAR: "SR",
  AED: "DH",
  BTC: "₿",
  ETH: "Ξ",
};

export const CURRENCY_NAMES: Record<SupportedCurrency, string> = {
  USD: "US Dollar",
  IDR: "Rupiah",
  EUR: "Euro",
  GBP: "Pound Sterling",
  JPY: "Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  HKD: "Hong Kong Dollar",
  NZD: "New Zealand Dollar",
  SGD: "Singapore Dollar",
  KRW: "South Korean Won",
  INR: "Indian Rupee",
  BRL: "Brazilian Real",
  RUB: "Russian Ruble",
  ZAR: "South African Rand",
  TRY: "Turkish Lira",
  PLN: "Polish Złoty",
  PHP: "Philippine Peso",
  THB: "Thai Baht",
  MYR: "Malaysian Ringgit",
  VND: "Vietnamese Đồng",
  SAR: "Saudi Riyal",
  AED: "UAE Dirham",
  BTC: "Bitcoin",
  ETH: "Ethereum",
};

export function formatCurrency(
  usdVal: number,
  currency: SupportedCurrency,
  rates: Record<string, number>
): string {
  const rate = rates[currency] || 1;
  const converted = usdVal * rate;
  const symbol = CURRENCY_SYMBOLS[currency] || "";

  if (currency === "IDR" || currency === "VND") {
    if (converted >= 1000) {
      return `${symbol} ${Math.round(converted).toLocaleString("id-ID")}`;
    } else if (converted >= 1) {
      return `${symbol} ${converted.toFixed(2).replace(".", ",")}`;
    } else {
      return `${symbol} ${converted.toFixed(6).replace(".", ",")}`;
    }
  }

  if (currency === "BTC" || currency === "ETH") {
    if (converted >= 1) {
      return `${symbol}${converted.toLocaleString(undefined, { minimumFractionDigits: 4, maximumFractionDigits: 4 })}`;
    }
    return `${symbol}${converted.toFixed(7)}`;
  }

  let minFraction = 2;
  let maxFraction = 2;
  if (currency === "JPY" || currency === "KRW") {
    minFraction = 0;
    maxFraction = 0;
  }

  if (converted >= 1000) {
    return `${symbol}${Math.round(converted).toLocaleString(undefined)}`;
  } else if (converted >= 1) {
    return `${symbol}${converted.toLocaleString(undefined, { minimumFractionDigits: minFraction, maximumFractionDigits: maxFraction })}`;
  } else if (converted >= 0.0001) {
    return `${symbol}${converted.toLocaleString(undefined, { minimumFractionDigits: 4, maximumFractionDigits: 4 })}`;
  } else {
    return `${symbol}${converted.toFixed(7)}`;
  }
}

const baseTranslations: Record<string, Record<string, string>> = {
  id: {
    // Navigation
    navMarkets: "Pasar Kripto",
    navPortfolio: "Portofolio Saya",
    navWatchlist: "Daftar Pantau",
    navConverter: "Konverter",
    navAdvisor: "Konsultan AI",
    navExchanges: "API Bursa",
    searchPlaceholder: "Cari koin...",
    searchClear: "Hapus",

    // Global Stats
    statCryptos: "Koin Kripto",
    statExchanges: "Bursa",
    statMarketCap: "Kapitalisasi Pasar",
    statVol24h: "Volume 24j",
    statDominance: "Dominasi",
    statGas: "Biaya Gas",

    // Market Overview general
    tabAllCoins: "Semua Koin",
    tabTrending: "Sedang Tren 🔥",
    tabGainers: "Kenaikan Terbesar 🟢",
    tabLosers: "Penurunan Terbesar 🔴",
    tabHighestVolume: "Volume Tertinggi 📊",
    sectorAll: "Semua Sektor",
    sectorLayer1: "Layer 1",
    sectorDeFi: "DeFi",
    sectorMeme: "Meme",
    sectorLayer2: "Layer 2",
    sectorAI: "Kecerdasan Buatan (AI)",
    sectorGaming: "Gaming & Web3",

    // Table headers
    colCoin: "Koin",
    colPrice: "Harga",
    col1h: "1j",
    col24h: "24j",
    col7d: "7h",
    colMarketCap: "Kapitalisasi Pasar",
    colVolume: "Volume (24j)",
    colSupply: "Suplai Beredar",
    colSparkline: "Tren (7h)",
    colAction: "Aksi",

    // Detail Modal
    modalRank: "Peringkat",
    modalMaxSupply: "Maks Suplai",
    modalInfinite: "Tak Terbatas",
    modalDescription: "Deskripsi Proyek",
    modalAiAnalysis: "Analisis Pasar Kecerdasan Buatan (AI)",
    modalRequestAi: "Dapatkan Analisis AI Komprehensif",
    modalLoadingAi: "Menganalisis pergerakan on-chain koin dengan Gemini-3.5-Flash...",
    modalAiTip: "Tip: Analisis didasarkan pada harga real-time, volume, dan data pesanan on-chain.",

    // Portfolio
    portHeader: "Lacak Portofolio Kripto Anda",
    portDesc: "Kelola aset, pantau harga beli rata-rata, hitung laba bersih, dan pantau rugi untung secara real-time.",
    portBalance: "Total Saldo",
    portProfit24h: "Keuntungan Bersih",
    portAddTransaction: "Tambah Transaksi Baru",
    portFormType: "Jenis Transaksi",
    portBuy: "Beli",
    portSell: "Jual",
    portQty: "Jumlah",
    portPrice: "Harga Transaksi (USD)",
    portSubmit: "Simpan Transaksi",
    portHoldings: "Aset Dimiliki",
    portLastTransactions: "Aktivitas Terakhir",
    portNoHoldings: "Belum ada transaksi. Tambahkan transaksi pertama Anda di atas untuk melacak laba untung rugi!",
    portAvgPrice: "Harga Rata-Rata Beli",
    portNetProfit: "Laba Bersih",

    // Watchlist
    watchHeader: "Daftar Pantau Personal Anda",
    watchDesc: "Kustomisasi daftar koin favorit Anda untuk pemantauan instan dan lincah tanpa kebisingan sektor.",
    watchNoCoins: "Daftar pantau Anda kosong. Silakan bintangi koin di menu Pasar Kripto!",

    // Converter
    convHeader: "Konverter Kripto Real-Time Multi-Aset",
    convDesc: "Kalkulator konversi instan antara koin digital favorit Anda dan berbagai mata uang fiat dunia.",
    convInputAmount: "Jumlah Koin",
    convSelectCoin: "Pilih Koin Asal",
    convTargetCurrency: "Ke Mata Uang",
    convResult: "Hasil Konversi",

    // Advisor
    advHeader: "Konsultan AI Portofolio Anda",
    advDesc: "Dapatkan strategi diversifikasi, tips manajemen risiko, penjelasan tokenomik, dan laporan pasar langsung dari asisten kecerdasan buatan Gemini.",
    advInputPlaceholder: "Contoh: Bagaimana rincian portofolio ideal untuk koin AI dan DeFi?",
    advSend: "Kirim",
    advClear: "Bersihkan Obrolan",
    advDisclaimer: "Pengingat: Investasi aset kripto sangat volatil. Semua analisis asisten AI bersifat edukatif dan bukan merupakan saran finansial profesional resmi.",
  },
  en: {
    // Navigation
    navMarkets: "Crypto Markets",
    navPortfolio: "My Portfolio",
    navWatchlist: "Watchlist",
    navConverter: "Converter",
    navAdvisor: "AI Advisor",
    navExchanges: "Exchange APIs",
    searchPlaceholder: "Search coin...",
    searchClear: "Clear",

    // Global Stats
    statCryptos: "Cryptos",
    statExchanges: "Exchanges",
    statMarketCap: "Market Cap",
    statVol24h: "24h Volume",
    statDominance: "Dominance",
    statGas: "Gas Price",

    // Market Overview general
    tabAllCoins: "All Coins",
    tabTrending: "Trending 🔥",
    tabGainers: "Top Gainers 🟢",
    tabLosers: "Top Losers 🔴",
    tabHighestVolume: "Highest Volume 📊",
    sectorAll: "All Sectors",
    sectorLayer1: "Layer 1",
    sectorDeFi: "DeFi",
    sectorMeme: "Meme",
    sectorLayer2: "Layer 2",
    sectorAI: "Artificial Intelligence (AI)",
    sectorGaming: "Gaming & Web3",

    // Table headers
    colCoin: "Coin",
    colPrice: "Price",
    col1h: "1h",
    col24h: "24h",
    col7d: "7d",
    colMarketCap: "Market Cap",
    colVolume: "Volume (24h)",
    colSupply: "Circulating Supply",
    colSparkline: "Last 7 Days",
    colAction: "Action",

    // Detail Modal
    modalRank: "Rank",
    modalMaxSupply: "Max Supply",
    modalInfinite: "Infinite",
    modalDescription: "Project Description",
    modalAiAnalysis: "Artificial Intelligence (AI) Market Analysis",
    modalRequestAi: "Retrieve Full AI Intelligence Report",
    modalLoadingAi: "Analyzing coin's on-chain movements with Gemini-3.5-Flash...",
    modalAiTip: "Tip: Analysis is calculated against real-time spot pricing, trading volume, and relative order logs.",

    // Portfolio
    portHeader: "Track Your Crypto Holdings",
    portDesc: "Track transaction averages, net profitability, real-time balances, and relative yield percentages seamlessly.",
    portBalance: "Total Balance",
    portProfit24h: "Net Profits",
    portAddTransaction: "Add New Transaction",
    portFormType: "Transaction Type",
    portBuy: "Buy",
    portSell: "Sell",
    portQty: "Quantity",
    portPrice: "Purchase Price (USD)",
    portSubmit: "Save Transaction",
    portHoldings: "Asset Portfolio",
    portLastTransactions: "Activity History",
    portNoHoldings: "Your portfolio is currently empty. Record buy or sell trades above to begin tracking balances and profits!",
    portAvgPrice: "Avg Purchase Price",
    portNetProfit: "Net Profit",

    // Watchlist
    watchHeader: "Your Personalized Watchlist",
    watchDesc: "Curate a focus-list of custom digital currencies to stay ahead of high-impact price movements.",
    watchNoCoins: "Your watchlist has no bookmarked assets. Star an item in the Crypto Markets tab to add it!",

    // Converter
    convHeader: "Real-Time Multi-Asset Convert Engine",
    convDesc: "Instantly translate digital asset valuations against global fiat currencies and major alternative crypto tickers.",
    convInputAmount: "Token Amount",
    convSelectCoin: "Source Asset",
    convTargetCurrency: "Target Currency",
    convResult: "Equivalent Valuation",

    // Advisor
    advHeader: "AI Web3 Portfolio Advisor",
    advDesc: "Access personalized tokenomics explainers, structural risk reviews, and yield diversification planning using Gemini Web3 Intelligence.",
    advInputPlaceholder: "E.g., Map out a resilient mid-cap Web3 portfolio allocation strategy.",
    advSend: "Send",
    advClear: "Clear Board",
    advDisclaimer: "Risk Note: Crypto-asset trading involves considerable price volatility. Output from our custom AI assistant is purely educational and does not constitute financial advice.",
  },
  de: {
    navMarkets: "Kryptomärkte",
    navPortfolio: "Mein Portfolio",
    navWatchlist: "Beobachtungsliste",
    navConverter: "Konverter",
    navAdvisor: "KI-Berater",
    navExchanges: "Börsen-APIs",
    searchPlaceholder: "Münze suchen...",
    searchClear: "Löschen",
    statCryptos: "Kryptos",
    statExchanges: "Börsen",
    statMarketCap: "Marktkapitalisierung",
    statVol24h: "24h Vol",
    statDominance: "Dominanz",
    statGas: "Gasgebühr",
    tabAllCoins: "Alle Münzen",
    tabTrending: "Trending 🔥",
    tabGainers: "Top-Gewinner 🟢",
    tabLosers: "Top-Verlierer 🔴",
    tabHighestVolume: "Höchstes Volumen 📊",
    sectorAll: "Alle Sektoren",
    sectorLayer1: "Layer 1",
    sectorDeFi: "DeFi",
    sectorMeme: "Meme",
    sectorLayer2: "Layer 2",
    sectorAI: "Künstliche Intelligenz (KI)",
    sectorGaming: "Gaming & Web3",
    colCoin: "Münze",
    colPrice: "Preis",
    col1h: "1std",
    col24h: "24std",
    col7d: "7t",
    colMarketCap: "Marktkapitalisierung",
    colVolume: "Volumen (24std)",
    colSupply: "Umlaufbestand",
    colSparkline: "Letzte 7 Tage",
    colAction: "Aktion",
    modalRank: "Rang",
    modalMaxSupply: "Max. Vorrat",
    modalInfinite: "Unendlich",
    modalDescription: "Projektbeschreibung",
    modalAiAnalysis: "Marktanalyse der Künstlichen Intelligenz (KI)",
    modalRequestAi: "Vollständigen KI-Bericht abrufen",
    modalLoadingAi: "On-Chain-Münzendaten analysieren mit Gemini-3.5-Flash...",
    modalAiTip: "Tipp: Die Analyse erfolgt auf Basis von Echtzeit-Münzpreis, Volumen und On-Chain-Orderbüchern.",
    portHeader: "Verfolgen Sie Ihre Kryptobestände",
    portDesc: "Verwalten Sie Konten, überwachen Sie Durchschnittspreise, berechnen Sie Nettogewinne und verfolgen Sie Renditen.",
    portBalance: "Gesamtsaldo",
    portProfit24h: "Nettogewinn",
    portAddTransaction: "Neue Transaktion hinzufügen",
    portFormType: "Transaktionstyp",
    portBuy: "Kauf",
    portSell: "Verkauf",
    portQty: "Menge",
    portPrice: "Kaufpreis (USD)",
    portSubmit: "Transaktion speichern",
    portHoldings: "Portfolio-Anlagen",
    portLastTransactions: "Aktivitätsverlauf",
    portNoHoldings: "Ihr Portfolio ist leer. Registrieren Sie Käufe oder Verkäufe, um Bestände zu verfolgen!",
    portAvgPrice: "Durchschnittskaufpreis",
    portNetProfit: "Nettogewinn",
    watchHeader: "Ihre persönliche Beobachtungsliste",
    watchDesc: "Stellen Sie eine personalisierte Favoritenliste zusammen, um Preisänderungen schnell zu verfolgen.",
    watchNoCoins: "Ihre Liste ist leer. Klicken Sie im Marktmenü auf den Stern einer Münze!",
    convHeader: "Echtzeit-Multiwährungs-Konverter",
    convDesc: "Rechnen Sie digitale Vermögenswerte sofort in traditionelle Fiat-Währungen oder wichtigste Kryptowährungs-Ticker um.",
    convInputAmount: "Token-Menge",
    convSelectCoin: "Ursprüngliche Münze",
    convTargetCurrency: "Zielwährung",
    convResult: "Gleichwertiger Wert",
    advHeader: "KI-Web3-Portfolio-Berater",
    advDesc: "Erhalten Sie Diversifizierungsstrategien, Tokenomics-Erklärungen und Risikomanagement-Tipps direkt vom Gemini KI-Assistenten.",
    advInputPlaceholder: "Z.B.: Erstellen Sie einen soliden KI- und DeFi-Portfolioverteilungsplan.",
    advSend: "Senden",
    advClear: "Verlauf löschen",
    advDisclaimer: "Wichtiger Hinweis: Kryptoökosysteme sind hochvolatiler Natur. KI-Kommentare dienen ausschließlich Bildungszwecken und stellen keine Finanzberatung dar.",
  },
  es: {
    navMarkets: "Mercados Cripto",
    navPortfolio: "Mi Portafolio",
    navWatchlist: "Lista de Seguimiento",
    navConverter: "Convertidor",
    navAdvisor: "Asesor IA",
    navExchanges: "APIs de Intercambio",
    searchPlaceholder: "Buscar moneda...",
    searchClear: "Limpiar",
    statCryptos: "Criptos",
    statExchanges: "Intercambios",
    statMarketCap: "Cap. de Mercado",
    statVol24h: "Volumen 24h",
    statDominance: "Dominancia",
    statGas: "Precio de Gas",
    tabAllCoins: "Todas las Monedas",
    tabTrending: "Tendencia 🔥",
    tabGainers: "Mayores Ganancias 🟢",
    tabLosers: "Mayores Pérdidas 🔴",
    tabHighestVolume: "Mayor Volumen 📊",
    sectorAll: "Todos los Sectores",
    sectorLayer1: "Layer 1",
    sectorDeFi: "DeFi",
    sectorMeme: "Meme",
    sectorLayer2: "Layer 2",
    sectorAI: "Inteligencia Artificial (IA)",
    sectorGaming: "Gaming y Web3",
    colCoin: "Moneda",
    colPrice: "Precio",
    col1h: "1h",
    col24h: "24h",
    col7d: "7d",
    colMarketCap: "Cap. de Mercado",
    colVolume: "Volumen (24h)",
    colSupply: "Suministro Circulante",
    colSparkline: "Últimos 7 Días",
    colAction: "Acción",
    modalRank: "Rango",
    modalMaxSupply: "Suministro Max",
    modalInfinite: "Infinito",
    modalDescription: "Descripción del Proyecto",
    modalAiAnalysis: "Análisis de Mercado con Inteligencia Artificial (IA)",
    modalRequestAi: "Obtener Informe Completo de IA",
    modalLoadingAi: "Analizando movimientos on-chain de criptomonedas con Gemini-3.5-Flash...",
    modalAiTip: "Consejo: El análisis se calcula en base al precio spot en tiempo real, volumen de transacciones y registros de libro de órdenes.",
    portHeader: "Siga su Cartera de Activos",
    portDesc: "Gestione transacciones, compruebe el precio de compra promedio, calcule ganancia neta e ingresos reales.",
    portBalance: "Saldo Total",
    portProfit24h: "Ganancias Netas",
    portAddTransaction: "Registrar Nueva Transacción",
    portFormType: "Tipo de Transacción",
    portBuy: "Comprar",
    portSell: "Vender",
    portQty: "Cantidad",
    portPrice: "Precio Compra (USD)",
    portSubmit: "Guardar Transacción",
    portHoldings: "Activos en Cartera",
    portLastTransactions: "Últimas Actividades",
    portNoHoldings: "Su portafolio está vacío. ¡Registre transacciones arriba para medir su rendimiento hoy mismo!",
    portAvgPrice: "Precio Promedio de Compra",
    portNetProfit: "Ganancia Neta",
    watchHeader: "Lista de Seguimiento Personal",
    watchDesc: "Configure su panel privado con sus activos digitales más importantes para alertas rápidas.",
    watchNoCoins: "Su lista de seguimiento está vacía. Seleccione la estrella de una cripto en mercados.",
    convHeader: "Convertidor Multi-Activos en Tiempo Real",
    convDesc: "Traduzca al instante valoraciones de activos digitales contra divisas fiat tradicionales y tokens principales.",
    convInputAmount: "Monto de Token",
    convSelectCoin: "Moneda de Origen",
    convTargetCurrency: "Convertir A",
    convResult: "Resultado Equivalente",
    advHeader: "Asistente IA de Inversión Web3",
    advDesc: "Obtenga consejos de asignación de activos, tokenomics y directrices de mitigación de pérdidas directamente del potente modelo Gemini.",
    advInputPlaceholder: "Ejemplo: Planifique una distribución óptima de portafolio de mediano plazo en IA y DeFi.",
    advSend: "Enviar",
    advClear: "Vaciar Chat",
    advDisclaimer: "Nota de Riesgo: Los mercados cripto conllevan una alta volatilidad. El análisis de nuestra inteligencia artificial cumple funciones puramente educativas y no constituye consejo financiero formal.",
  },
  fr: {
    navMarkets: "Marchés Crypto",
    navPortfolio: "Mon Portefeuille",
    navWatchlist: "Liste de Surveillance",
    navConverter: "Convertisseur",
    navAdvisor: "Conseiller IA",
    navExchanges: "API de Plateformes",
    searchPlaceholder: "Rechercher...",
    searchClear: "Effacer",
    portBalance: "Solde Total",
    portProfit24h: "Bénéfices Nets",
  },
  it: {
    navMarkets: "Mercati Crypto",
    navPortfolio: "Mio Portafoglio",
    navWatchlist: "Watchlist",
    navConverter: "Convertitore",
    navAdvisor: "Consulente IA",
    navExchanges: "API Exchange",
    searchPlaceholder: "Cerca...",
    searchClear: "Cancella",
    portBalance: "Saldo Totale",
    portProfit24h: "Profitto Netto",
  },
  pt: {
    navMarkets: "Mercados Crypto",
    navPortfolio: "Meu Portfólio",
    navWatchlist: "Lista de Observação",
    navConverter: "Conversor",
    navAdvisor: "Consultor de IA",
    navExchanges: "APIs de Câmbio",
    searchPlaceholder: "Buscar...",
    searchClear: "Limpar",
    portBalance: "Saldo Total",
    portProfit24h: "Lucros Líquidos",
  },
  ru: {
    navMarkets: "Крипто Рынки",
    navPortfolio: "Мой Портфель",
    navWatchlist: "Список наблюдения",
    navConverter: "Конвертер",
    navAdvisor: "ИИ Советник",
    navExchanges: "API Бирж",
    searchPlaceholder: "Искать...",
    searchClear: "Очистить",
    portBalance: "Общий баланс",
    portProfit24h: "Чистая прибыль",
  },
  zh: {
    navMarkets: "加密板块",
    navPortfolio: "投资组合",
    navWatchlist: "自选频道",
    navConverter: "兑换计算",
    navAdvisor: "智能投顾",
    navExchanges: "平台接口",
    searchPlaceholder: "输入代币...",
    searchClear: "重置",
    portBalance: "总余额",
    portProfit24h: "净利润",
  },
  ja: {
    navMarkets: "暗号通貨市場",
    navPortfolio: "マイ・ポートフォリオ",
    navWatchlist: "マイリスト",
    navConverter: "両替用窓口",
    navAdvisor: "AIアシスタント",
    navExchanges: "取引所API",
    searchPlaceholder: "通貨を検索...",
    searchClear: "クリア",
    portBalance: "総資産残高",
    portProfit24h: "純正利益分",
  },
  ko: {
    navMarkets: "암호화폐 시장",
    navPortfolio: "포트폴리오",
    navWatchlist: "관심토큰 목록",
    navConverter: "통화 컨버터",
    navAdvisor: "AI 포트폴리오 조언",
    navExchanges: "API 통합",
    searchPlaceholder: "종목 검색...",
    searchClear: "초기화",
    portBalance: "총평가 금액",
    portProfit24h: "순이익액",
  },
  ar: {
    navMarkets: "أسواق العملات",
    navPortfolio: "محفظتي الاستثمارية",
    navWatchlist: "قائمة المتابعة",
    navConverter: "المحول الفوري",
    navAdvisor: "مستشار المحفظة الذكي",
    navExchanges: "وصلات بورصات منوعة",
    searchPlaceholder: "ابحث عن العملات الكبرى...",
    searchClear: "تصفية",
    portBalance: "إجمالي الرصيد الراهن",
    portProfit24h: "الكسب الصافي للحقيبة",
  },
  hi: {
    navMarkets: "क्रिप्टो बाज़ार दरें",
    navPortfolio: "मेरा निवेश पोर्टफोलियो",
    navWatchlist: "सुरक्षित सूची",
    navConverter: "मुद्रा परिवर्तक",
    navAdvisor: "एआई सलाहकार",
    navExchanges: "मल्टी एक्सचेंज हบ",
    searchPlaceholder: "सिक्का खोजें...",
    searchClear: "मिटाएं",
    portBalance: "कुल मूल्य",
    portProfit24h: "शुद्ध लाभ",
  },
  tr: {
    navMarkets: "Kripto Piyasaları",
    navPortfolio: "Varlık Portföyüm",
    navWatchlist: "Takip Listesi",
    navConverter: "Kripto Çevirici",
    navAdvisor: "Yapay Zeka Danışmanı",
    navExchanges: "Canlı Borsa API",
    searchPlaceholder: "Aranacak coin...",
    searchClear: "Sıfırla",
    portBalance: "Toplam Bakiye",
    portProfit24h: "Net Kar/Zarar",
  },
  nl: {
    navMarkets: "Cryptomarkten",
    navPortfolio: "Mijn Portefeuille",
    navWatchlist: "Mijn Volglijst",
    navConverter: "Wissel-Calculator",
    navAdvisor: "AI Portefeuilleraad",
    navExchanges: "Systeem API's",
    searchPlaceholder: "Zoek direct...",
    searchClear: "Wissen",
    portBalance: "Totale Balans",
    portProfit24h: "Netto-Opbrengsten",
  },
  pl: {
    navMarkets: "Notowania Kryptowalut",
    navPortfolio: "Portfel Aktywów",
    navWatchlist: "Zapisane Waluty",
    navConverter: "Szybki Przelicznik",
    navAdvisor: "Sztuczna Inteligencja",
    navExchanges: "Konektory API",
    searchPlaceholder: "Wyszukaj walutę...",
    searchClear: "Wyczyść",
    portBalance: "Suma Środków",
    portProfit24h: "Zysk netto",
  },
  th: {
    navMarkets: "ตารางราคาสินทรัพย์",
    navPortfolio: "จัดการพอร์ตของฉัน",
    navWatchlist: "รายการเฝ้าสังเกตการณ์",
    navConverter: "คำนวณอัตราแลกเปลี่ยน",
    navAdvisor: "ที่ปรึกษา AI อัจฉริยะ",
    navExchanges: "เชื่อมต่อตลาด live",
    searchPlaceholder: "ค้นหาชื่อเหรียญ...",
    searchClear: "รีเซ็ต",
    portBalance: "มูลค่าพอร์ตรวมทั้งหมด",
    portProfit24h: "กำไรสุทธิวันปัจจุบัน",
  },
  vi: {
    navMarkets: "Sàn giao dịch liên tục",
    navPortfolio: "Sổ tay danh mục",
    navWatchlist: "Kênh theo dõi nhanh",
    navConverter: "Công thức hoán đổi",
    navAdvisor: "Trực quan tư vấn AI",
    navExchanges: "Hệ thống API bối cảnh",
    searchPlaceholder: "Tìm kiếm mã giao dịch...",
    searchClear: "Xóa hết",
    portBalance: "Tổng giá trị tài sản",
    portProfit24h: "Lợi nhuận ròng tích lũy",
  }
};

export const TRANSLATIONS = new Proxy(baseTranslations, {
  get(target, lang: string) {
    const requested = target[lang] || target["en"];
    return new Proxy(requested, {
      get(subTarget, key: string) {
        return subTarget[key] || target["en"][key] || key;
      }
    });
  }
}) as unknown as Record<SupportedLang, Record<string, string>>;
